package Calculadora;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;

 // @author Daniel Mancia DEV

public class VistaCalculadora extends javax.swing.JFrame {
    double N1 = 0; 
    double N2 = 0; 
    String operador = ""; 
    boolean esResultado = false;

    public VistaCalculadora() {
        initComponents();
        this.setSize(296, 335); 
        this.setLocationRelativeTo(null);
        
        PantallaResultados.requestFocusInWindow();
        PantallaResultados.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent evt) {
                char c = evt.getKeyChar();
                if (c =='0') {
                    PantallaResultados.setText(PantallaResultados.getText() + "0");
                }
                else if(c=='1'){
                    PantallaResultados.setText(PantallaResultados.getText() + "1");
                }
                else if(c=='2'){
                    PantallaResultados.setText(PantallaResultados.getText() + "2");
                }
                else if(c=='3'){
                    PantallaResultados.setText(PantallaResultados.getText() + "3");
                }
                else if(c=='4'){
                    PantallaResultados.setText(PantallaResultados.getText() + "4");
                }
                else if(c=='5'){
                    PantallaResultados.setText(PantallaResultados.getText() + "5");
                }
                else if(c=='6'){
                    PantallaResultados.setText(PantallaResultados.getText() + "6");
                }
                else if(c=='7'){
                    PantallaResultados.setText(PantallaResultados.getText() + "7");
                }
                else if(c=='8'){
                    PantallaResultados.setText(PantallaResultados.getText() + "8");
                }
                else if(c=='9'){
                    PantallaResultados.setText(PantallaResultados.getText() + "9");
                }
                else if(c=='.'){
                    PantallaResultados.setText(PantallaResultados.getText() + ".");
                }
                else if(c=='+'){
                    operador = String.valueOf(c);
                    N1 = Double.parseDouble(PantallaResultados.getText());
                    PantallaResultados.setText("");
                }
                else if(c=='-'){
                    operador = String.valueOf(c);
                    N1 = Double.parseDouble(PantallaResultados.getText());
                    PantallaResultados.setText("");
                }
                else if(c=='x'){
                    operador = String.valueOf(c);
                    N1 = Double.parseDouble(PantallaResultados.getText());
                    PantallaResultados.setText("");
                }
                else if(c=='/'){
                    operador = String.valueOf(c);
                    N1 = Double.parseDouble(PantallaResultados.getText());
                    PantallaResultados.setText("");
                }
                else if (c == '^') {
                    operador = "^2";
                    N1 = Double.parseDouble(PantallaResultados.getText());
                    PantallaResultados.setText("");
                }
                else if(c=='='|| c == KeyEvent.VK_ENTER){
                  btnIGUALActionPerformed(null);
                }
                evt.consume();  
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PantallaResultados = new javax.swing.JTextField();
        btn1 = new javax.swing.JButton();
        btnDIVISION = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btnPUNTO = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnIGUAL = new javax.swing.JButton();
        btnMAS = new javax.swing.JButton();
        btnELEVARAL2 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btnMULTIPLICACION = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btnAC = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btnMENOS = new javax.swing.JButton();
        btnDEL = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(8, 206, 151));
        setMaximumSize(null);
        setMinimumSize(new java.awt.Dimension(270, 251));
        setPreferredSize(new java.awt.Dimension(270, 251));
        setSize(new java.awt.Dimension(270, 251));

        jPanel1.setBackground(new java.awt.Color(25, 33, 40));

        PantallaResultados.setBackground(new java.awt.Color(204, 204, 204));
        PantallaResultados.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PantallaResultados.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        PantallaResultados.setBorder(null);

        btn1.setBackground(new java.awt.Color(102, 102, 102));
        btn1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn1.setForeground(new java.awt.Color(255, 255, 255));
        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btnDIVISION.setBackground(new java.awt.Color(102, 102, 102));
        btnDIVISION.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDIVISION.setForeground(new java.awt.Color(255, 255, 255));
        btnDIVISION.setText("/");
        btnDIVISION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDIVISIONActionPerformed(evt);
            }
        });

        btn2.setBackground(new java.awt.Color(102, 102, 102));
        btn2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn2.setForeground(new java.awt.Color(255, 255, 255));
        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btnPUNTO.setBackground(new java.awt.Color(102, 102, 102));
        btnPUNTO.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPUNTO.setForeground(new java.awt.Color(255, 255, 255));
        btnPUNTO.setText(".");
        btnPUNTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPUNTOActionPerformed(evt);
            }
        });

        btn3.setBackground(new java.awt.Color(102, 102, 102));
        btn3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn3.setForeground(new java.awt.Color(255, 255, 255));
        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btnIGUAL.setBackground(new java.awt.Color(102, 102, 102));
        btnIGUAL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnIGUAL.setForeground(new java.awt.Color(255, 255, 255));
        btnIGUAL.setText("=");
        btnIGUAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIGUALActionPerformed(evt);
            }
        });

        btnMAS.setBackground(new java.awt.Color(102, 102, 102));
        btnMAS.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMAS.setForeground(new java.awt.Color(255, 255, 255));
        btnMAS.setText("+");
        btnMAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMASActionPerformed(evt);
            }
        });

        btnELEVARAL2.setBackground(new java.awt.Color(102, 102, 102));
        btnELEVARAL2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnELEVARAL2.setForeground(new java.awt.Color(255, 255, 255));
        btnELEVARAL2.setText("x^2");
        btnELEVARAL2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnELEVARAL2ActionPerformed(evt);
            }
        });

        btn4.setBackground(new java.awt.Color(102, 102, 102));
        btn4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn4.setForeground(new java.awt.Color(255, 255, 255));
        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btnMULTIPLICACION.setBackground(new java.awt.Color(102, 102, 102));
        btnMULTIPLICACION.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMULTIPLICACION.setForeground(new java.awt.Color(255, 255, 255));
        btnMULTIPLICACION.setText("x");
        btnMULTIPLICACION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMULTIPLICACIONActionPerformed(evt);
            }
        });

        btn5.setBackground(new java.awt.Color(102, 102, 102));
        btn5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn5.setForeground(new java.awt.Color(255, 255, 255));
        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btnAC.setBackground(new java.awt.Color(102, 255, 51));
        btnAC.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAC.setForeground(new java.awt.Color(255, 255, 255));
        btnAC.setText("AC");
        btnAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnACActionPerformed(evt);
            }
        });

        btn6.setBackground(new java.awt.Color(102, 102, 102));
        btn6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn6.setForeground(new java.awt.Color(255, 255, 255));
        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btnMENOS.setBackground(new java.awt.Color(102, 102, 102));
        btnMENOS.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMENOS.setForeground(new java.awt.Color(255, 255, 255));
        btnMENOS.setText("-");
        btnMENOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMENOSActionPerformed(evt);
            }
        });

        btnDEL.setBackground(new java.awt.Color(102, 255, 51));
        btnDEL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDEL.setForeground(new java.awt.Color(255, 255, 255));
        btnDEL.setText("DEL");
        btnDEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDELActionPerformed(evt);
            }
        });

        btn7.setBackground(new java.awt.Color(102, 102, 102));
        btn7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn7.setForeground(new java.awt.Color(255, 255, 255));
        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.setBackground(new java.awt.Color(102, 102, 102));
        btn8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn8.setForeground(new java.awt.Color(255, 255, 255));
        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn0.setBackground(new java.awt.Color(102, 102, 102));
        btn0.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn0.setForeground(new java.awt.Color(255, 255, 255));
        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        btn9.setBackground(new java.awt.Color(102, 102, 102));
        btn9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn9.setForeground(new java.awt.Color(255, 255, 255));
        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Calculadora Básica");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PantallaResultados)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnPUNTO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(btn7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btn4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btn1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btn5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnELEVARAL2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDIVISION, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDEL, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(btnMENOS, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnMAS, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnMULTIPLICACION, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnAC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnIGUAL, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PantallaResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDEL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnELEVARAL2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDIVISION, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnMULTIPLICACION, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnMENOS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMAS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPUNTO, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIGUAL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnACActionPerformed
        N1 = 0;
        N2 = 0;
        operador = "";
        this.PantallaResultados.setText(""); 
        PantallaResultados.requestFocusInWindow();
    }//GEN-LAST:event_btnACActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        PantallaResultados.setText(PantallaResultados.getText() + "9");
        PantallaResultados.requestFocusInWindow();
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        PantallaResultados.setText(PantallaResultados.getText() + "0");
        PantallaResultados.requestFocusInWindow();
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnPUNTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPUNTOActionPerformed
        PantallaResultados.setText(PantallaResultados.getText() + ".");
        PantallaResultados.requestFocusInWindow();
    }//GEN-LAST:event_btnPUNTOActionPerformed

    private void btnIGUALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIGUALActionPerformed
        PantallaResultados.requestFocusInWindow();
        if (!operador.isEmpty()) {
            N2 = Double.parseDouble(this.PantallaResultados.getText());
            switch (operador) {
                case "+":
                    N1 += N2;
                    break;
                    
                case "-":
                    N1 -= N2;
                    break;
                    
                case "x":
                    N1 *= N2;
                    break;
                    
                case "/":
                    if (N2 != 0) {
                        N1 /= N2;
                    } else {
                        this.PantallaResultados.setText("Error no se puede dividir entre 0");
                        return;
                    }
                    break;
                    
                case "^2":
                    N1 = Math.pow(N1, 2);
                    break;
                    
                default:
                    N1 = N2; 
                    break;
            }

            if (N1 == (int) N1) {
                this.PantallaResultados.setText(String.valueOf((int) N1));
            }else {
                DecimalFormat df = new DecimalFormat("#.##");
                this.PantallaResultados.setText(df.format(N1));
            }
            N2 = 0;
            operador = "";
            PantallaResultados.requestFocusInWindow();
            esResultado = true;
        }
    }//GEN-LAST:event_btnIGUALActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        PantallaResultados.setText(PantallaResultados.getText() + "1");
        PantallaResultados.requestFocusInWindow();
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        PantallaResultados.setText(PantallaResultados.getText() + "2");
        PantallaResultados.requestFocusInWindow();
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        PantallaResultados.setText(PantallaResultados.getText() + "3");
        PantallaResultados.requestFocusInWindow();
    }//GEN-LAST:event_btn3ActionPerformed

    private void btnMASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMASActionPerformed
        if (this.PantallaResultados.getText().isEmpty()) {
        return; 
        }
        if (!operador.isEmpty()) {
            btnIGUALActionPerformed(null);
        }
        N1 = Double.parseDouble(this.PantallaResultados.getText());
        operador = "+";
        this.PantallaResultados.setText(""); 
        PantallaResultados.requestFocusInWindow(); 
    }//GEN-LAST:event_btnMASActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        PantallaResultados.setText(PantallaResultados.getText() + "4");
        PantallaResultados.requestFocusInWindow();
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        PantallaResultados.setText(PantallaResultados.getText() + "5");
        PantallaResultados.requestFocusInWindow();
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        PantallaResultados.setText(PantallaResultados.getText() + "6");
        PantallaResultados.requestFocusInWindow();
    }//GEN-LAST:event_btn6ActionPerformed

    private void btnMENOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMENOSActionPerformed
        if (this.PantallaResultados.getText().isEmpty()) {
        return; 
        }
        if (!operador.isEmpty()) {
            btnIGUALActionPerformed(null);
        }
        N1 = Double.parseDouble(this.PantallaResultados.getText());
        operador = "-";
        this.PantallaResultados.setText(""); 
        PantallaResultados.requestFocusInWindow();
    }//GEN-LAST:event_btnMENOSActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        PantallaResultados.setText(PantallaResultados.getText() + "7");
        PantallaResultados.requestFocusInWindow();
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        PantallaResultados.setText(PantallaResultados.getText() + "8");
        PantallaResultados.requestFocusInWindow();
    }//GEN-LAST:event_btn8ActionPerformed

    private void btnMULTIPLICACIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMULTIPLICACIONActionPerformed
        if (this.PantallaResultados.getText().isEmpty()) {
        return; 
        }
        if (!operador.isEmpty()) {
            btnIGUALActionPerformed(null);
        }
        N1 = Double.parseDouble(this.PantallaResultados.getText());
        operador = "x";
        this.PantallaResultados.setText(""); 
        PantallaResultados.requestFocusInWindow();
    }//GEN-LAST:event_btnMULTIPLICACIONActionPerformed

    private void btnELEVARAL2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnELEVARAL2ActionPerformed
        if (this.PantallaResultados.getText().isEmpty()) {
        return;
        }
        if (!operador.isEmpty()) {
            btnIGUALActionPerformed(null);
        }
        N1 = Double.parseDouble(this.PantallaResultados.getText());
        operador = "^2";
        PantallaResultados.requestFocusInWindow();
    }//GEN-LAST:event_btnELEVARAL2ActionPerformed

    private void btnDIVISIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDIVISIONActionPerformed
        if (this.PantallaResultados.getText().isEmpty()) {
        return; 
        }
        if (!operador.isEmpty()) {
            btnIGUALActionPerformed(null);
        }
        N1 = Double.parseDouble(this.PantallaResultados.getText());
        operador = "/";
        this.PantallaResultados.setText(""); 
        PantallaResultados.requestFocusInWindow();
    }//GEN-LAST:event_btnDIVISIONActionPerformed

    private void btnDELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDELActionPerformed
        if (esResultado) {
        this.PantallaResultados.setText("");
        esResultado = false;  
        } else {
            String textoActual = this.PantallaResultados.getText();
            if (textoActual.length() > 0) {
                this.PantallaResultados.setText(textoActual.substring(0, textoActual.length() - 1));
            }
        }
         PantallaResultados.requestFocusInWindow();
    }//GEN-LAST:event_btnDELActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PantallaResultados;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnAC;
    private javax.swing.JButton btnDEL;
    private javax.swing.JButton btnDIVISION;
    private javax.swing.JButton btnELEVARAL2;
    private javax.swing.JButton btnIGUAL;
    private javax.swing.JButton btnMAS;
    private javax.swing.JButton btnMENOS;
    private javax.swing.JButton btnMULTIPLICACION;
    private javax.swing.JButton btnPUNTO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}